name: GreyNoise Indicator Import Scheduler
parameters:
    actions:
        configuration:
            greynoise_ti_import_bulk_a6513819:
                properties:
                    api_key:
                        required: true
                    max_indicator_count:
                        required: false
                        default_value: "100000"
                    query:
                        required: false
                        default_value: last_seen:1d
                    repository:
                        required: false
                        default_value: search-all
provision_on_install: true
trigger:
    next:
        - greynoise_ti_import_bulk_a6513819
    event: Schedule
    schedule:
        time_cycle: 0 3 */1 * *
        start_date: ""
        end_date: ""
        tz: America/New_York
        skip_concurrent: false
actions:
    greynoise_ti_import_bulk_a6513819:
        id: functions.greynoise-ti-import-to-ng-siem.greynoise-ti-import-bulk
        properties: {}
